baseURL = "https://elipsis.github.io/phaseweb/"
languageCode = "en-us"
title = "PhaseWorm"
publishDir = "docs"

[[menu.shortcuts]]
pre = "steam"
name = "Steam Store"
url = "https://store.steampowered.com/app/1287790/PhaseWorm/"
weight = 100

[[menu.shortcuts]]
pre = "twitter"
name = "PhaseWorm on Twitter"
url = "https://www.twitter.com/phaseworm"
weight = 101

[[menu.shortcuts]]
pre = "discord"
name = "Join the Discord"
url = "https://discordapp.com/invite/yJFyHPh"
weight = 102
